apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: elouadiabdelati/cooptation-frontend:0.0.2 # {"$imagepolicy": "flux-system:react"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: flux-system
spec:
  type: NodePort
  selector:
    app: react
  ports:
  - port: 3000
    targetPort: 80
