apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: flux-system
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: elouadiabdelati/cooptation-backend:0.0.1 # {"$imagepolicy": "flux-system:backend"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                 name: app-secret
                 key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: BD_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BD_URL
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: flux-system
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
